backend:
  name: github
  repo: greenmagicresort25/green-magic-resort
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage Content"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "home"
        fields:
          - label: "Welcome Heading"
            name: "welcome_heading"
            widget: "string"
